# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations

TYPE_CHECKING = False
VERSION_TUPLE = tuple[int | str, ...] if TYPE_CHECKING else object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.1.dev30+g82d2a69.d20231016"
__version_tuple__ = version_tuple = (0, 1, "dev30", "g82d2a69.d20231016")
